services:
  postgres_db:
    image: postgres:15-alpine
    container_name: booking_postgres
    restart: always
    env_file:
      - ./api/.env.dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      start_period: 10s
    networks:
      - booking_network

  prisma_studio:
    image: node:20-alpine
    container_name: booking_prisma_studio
    restart: always
    working_dir: /app
    volumes:
      - ./api/prisma:/app/prisma
    env_file:
      - ./api/.env.dev
    ports:
      - "5555:5555"
    command: >
      sh -c "apk add --no-cache socat && socat TCP-LISTEN:5555,fork,bind=0.0.0.0 TCP:127.0.0.1:5556 & npx -y prisma@7.8.0 studio --port 5556 --browser none --url postgresql://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres_db:5432/$${POSTGRES_DB}?schema=public"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - booking_network

  redis_cache:
    image: redis:7-alpine
    container_name: booking_redis
    restart: always
    ports:
      - "${REDIS_HOST_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - booking_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: booking_api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ./api/.env.dev
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - REDIS_HOST=redis_cache
      - TZ=Asia/Ho_Chi_Minh
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run dev"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - booking_network


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: booking_client
    restart: always
    ports:
      - "${CLIENT_PORT:-5173}:5173"   
    env_file:
      - ./client/.env.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      api:
        condition: service_started
    networks:
      - booking_network
      
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  booking_network:
    driver: bridge
