services:
  # 1. Cơ sở dữ liệu PostgreSQL
  postgres_db:
    image: postgres:15-alpine
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking_network

  # 2. Redis Cache để lưu OTP
  redis_cache:
    image: redis:7-alpine
    container_name: booking_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - booking_network

  # 3. Backend API Service (Chạy môi trường Dev)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: booking_api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ./api/.env.dev
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres_db:5432/booking?schema=public
      - REDIS_HOST=redis_cache
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - postgres_db
      - redis_cache
    networks:
      - booking_network

  # 4. Frontend Client Service
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: booking_client
  #   restart: always
  #   ports:
  #     - "${CLIENT_PORT:-3001}:3000"   # tạm giả định FE cũng chạy port 3000 bên trong container
  #   env_file:
  #     - ./client/.env.dev
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   depends_on:
  #     - api
  #   networks:
  #     - booking_network

volumes:
  postgres_data:
  redis_data:

networks:
  booking_network:
    driver: bridge