import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { userService } from "@/api/services/userService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "sonner";

interface AgentUser { id: string; email: string; role: string; status: string; createdAt: string; profile?: { fullName?: string | null; phoneNumber?: string | null; address?: string | null } | null }
const labels: Record<string, string> = { ACTIVE: "Đã duyệt", PENDING: "Chờ duyệt", INACTIVE: "Tạm ngưng", BANNED: "Đã khóa", REJECTED: "Từ chối" };

export default function AgentManagement() {
  const [agents, setAgents] = useState<AgentUser[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState<string | null>(null);
  useEffect(() => { userService.getAllUsers().then((response) => setAgents(response.data.filter((user: AgentUser) => user.role === "AGENT"))).catch(() => toast.error("Không thể tải đối tác")).finally(() => setLoading(false)); }, []);
  const updateStatus = async (agent: AgentUser, status: string) => { if (!window.confirm(`Chuyển ${agent.email} sang ${labels[status]}?`)) return; try { setUpdating(agent.id); const response = await userService.updateStatus(agent.id, status); setAgents((current) => current.map((item) => item.id === agent.id ? response.data : item)); toast.success("Đã cập nhật trạng thái đối tác"); } catch (error: any) { toast.error(error.response?.data?.message || "Không thể cập nhật đối tác"); } finally { setUpdating(null); } };
  const filtered = agents.filter((agent) => `${agent.email} ${agent.profile?.fullName || ""} ${agent.profile?.phoneNumber || ""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Duyệt đối tác</h1><p className="mt-1 text-muted-foreground">Duyệt, từ chối hoặc khóa tài khoản kinh doanh.</p></div><div className="relative max-w-sm"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="pl-9" placeholder="Tìm tên, email hoặc số điện thoại" /></div><div className="overflow-hidden rounded-xl border bg-white"><Table><TableHeader><TableRow><TableHead>Đối tác</TableHead><TableHead>Liên hệ</TableHead><TableHead>Ngày đăng ký</TableHead><TableHead>Trạng thái</TableHead><TableHead className="text-right">Thao tác</TableHead></TableRow></TableHeader><TableBody>{!loading && filtered.length ? filtered.map((agent) => <TableRow key={agent.id}><TableCell><div className="font-medium">{agent.profile?.fullName || "Chưa cập nhật tên"}</div><div className="text-xs text-muted-foreground">{agent.email}</div></TableCell><TableCell><div>{agent.profile?.phoneNumber || "Chưa có SĐT"}</div><div className="text-xs text-muted-foreground">{agent.profile?.address || "Chưa có địa chỉ"}</div></TableCell><TableCell>{new Date(agent.createdAt).toLocaleDateString("vi-VN")}</TableCell><TableCell><Badge variant={agent.status === "BANNED" || agent.status === "REJECTED" ? "destructive" : agent.status === "ACTIVE" ? "default" : "secondary"}>{labels[agent.status] || agent.status}</Badge></TableCell><TableCell className="text-right"><div className="flex justify-end gap-2">{agent.status === "PENDING" && <><Button size="sm" disabled={updating === agent.id} onClick={() => void updateStatus(agent, "ACTIVE")}>Duyệt</Button><Button size="sm" variant="destructive" disabled={updating === agent.id} onClick={() => void updateStatus(agent, "REJECTED")}>Từ chối</Button></>}{(agent.status === "BANNED" || agent.status === "REJECTED" || agent.status === "INACTIVE") && <Button size="sm" disabled={updating === agent.id} onClick={() => void updateStatus(agent, "ACTIVE")}>Kích hoạt</Button>}{agent.status === "ACTIVE" && <Button size="sm" variant="outline" className="text-destructive" disabled={updating === agent.id} onClick={() => void updateStatus(agent, "BANNED")}>Khóa</Button>}</div></TableCell></TableRow>) : <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">{loading ? "Đang tải..." : "Không có đối tác phù hợp."}</TableCell></TableRow>}</TableBody></Table></div></div>;
}
